negative_keywords:
  # 🚆 Transport / Train / Vehicles
  - "鉄道"
  - "電車"
  - "駅"
  - "川越駅"
  - "川越線"
  - "東武"
  - "西武"
  - "埼京線"
  - "新幹線"
  - "Saikyo Line"
  - "Rapid"
  - "train"
  - "列車"
  - "特急"
  - "急行"
  - "普通列車"
  - "快速"
  - "回送"
  - "機関車"
  - "乗車"
  - "走行"
  - "踏切"
  - "車窓"
  - "発車メロディー"
  - "バス"
  - "高速バス"
  - "中古車"
  - "車屋"
  - "Harley"
  - "ハーレーダビッドソン"
  - "バイク"
  - "motorcycle"
  - "bike"
  - "車両"
  - "custom"

  # 🎮 Games / Anime / Otaku culture
  - "ゲーム"
  - "game"
  - "match"
  - "試合"
  - "対戦"
  - "eスポーツ"
  - "FC"
  - "カルカソンヌ"
  - "部活動"
  - "アニメ"
  - "anime"
  - "マンガ"
  - "漫画"
  - "オタク"
  - "コスプレ"
  - "ゲーム実況"
  - "マイクラ"

  # 🎵 Music / Entertainment / Streaming
  - "音楽"
  - "演奏"
  - "吹奏楽"
  - "ライブ"
  - "レコード"
  - "BGM"
  - "リラックス"
  - "Relaxing"
  - "StudyMusic"
  - "勉強用"
  - "バンド"
  - "カラオケ"
  - "コンサート"
  - "ダンス"
  - "展示会"
  - "fullmovie"
  - "ototabi"
  - "ライブ"
  - "live camera"
  - "配信"
  - "生配信"
  - "VTuber"
  - "Vチューバー"
  - "ちいかわ"
  - "踊ってみた"
  - "歌ってみた"
  - "ラジオ"
  - "お笑い"
  - "漫才"
  - "映画"
  - "ドラマ"
  - "ドローン"

  # ⚽ Sports
  - "サッカー"
  - "soccer"
  - "football"
  - "フットボール"
  - "野球"
  - "baseball"
  - "中日"
  - "ドラゴンズ"
  - "ホームラン"
  - "バスケ"
  - "basketball"
  - "ハイライト"
  - "練習"
  - "practice"
  - "初心者"
  - "指導"
  - "部活"

  # 🏭 Work / Business / Promotion
  - "アルバイト"
  - "パート"
  - "求人"
  - "仕事"
  - "就職"
  - "転職"
  - "会社"
  - "会社紹介"
  - "企業"
  - "協会"
  - "展示会"
  - "イベント案内"
  - "不動産"
  - "CM"
  - "広告"
  - "PR"
  - "セミナー"
  - "説明会"
  - "相談"
  - "監修"

  # 💅 Beauty / Health / Shops
  - "美容"
  - "ホワイトニング"
  - "脱毛"
  - "エステ"
  - "マッサージ"
  - "整体"
  - "教会"
  - "ドラッグストア"
  - "薬局"
  - "病院"
  - "献血"
  - "クリニック"
  - "歯科"
  - "スーパー"
  - "コンビニ"
  - "Tシャツ"
  - "ファッション"

  # 📰 News / Politics / Incidents
  - "ニュース"
  - "報道"
  - "政治"
  - "議会"
  - "選挙"
  - "事件"
  - "事故"
  - "災害"
  - "火事"
  - "刑務所"
  - "裁判"
  - "人口"

  # 🏫 School / Education
  - "学校"
  - "school"
  - "中学校"
  - "高校"
  - "大学"
  - "専門学校"
  - "教室"
  - "授業"
  - "入学式"
  - "卒業式"
  - "文化祭"
  - "体育祭"
  - "地理"

  # 🐶 Pets / Daily life vlogs
  - "犬"
  - "dog"
  - "cat"
  - "猫"
  - "ペット"
  - "ペットショップ"
  - "日常"
  - "daily life"
  - "lifestyle"
  - "家族"
  - "子供"
  - "vlog"
  - "ガーデニング"
  - "家庭菜園"
  - "観葉植物"
  - "栽培"
  - "DIY"

  # 🍜 Food (non-tourism cooking)
  - "定食"
  - "ラーメン"
  - "もつ煮"
  - "居酒屋"
  - "料理"
  - "cooking"
  - "レシピ"
  - "recipe"
  - "food vlog"

  # 🏠 Housing / Urban / Construction
  - "川越シェフ"
  - "書店"
  - "エレベーター"
  - "マンション"
  - "住宅街"
  - "アパート"
  - "団地"
  - "住宅"
  - "工場"
  - "工事"
  - "建設"
  - "建築"
  - "リフォーム"

  # 🌤️ Weather / Environment
  - "天気"
  - "気温"
  - "暑さ"
