heritage:
  - "temple"
  - "寺"
  - "shrine"
  - "神社"
  - "castle"
  - "城"
  - "蔵"           
  - "時の鐘"           
  - "喜多院"                      
  - "歴史"  
  - "historic"
  - "traditional"
  - "将軍"
  - "Shogun"
  - "古い"
  - "old"
  - "昔"
  - "chopsticks"

food:
  - "食"
  - "飯"
  - "グルメ"
  - "市場"
  - "お店"
  - "food"
  - "料理"
  - "ランチ"
  - "ディナー"
  - "絶品"
  - "ramen"
  - "ラーメン"
  - "うどん"
  - "パスタ"
  - "sushi"
  - "寿司"
  - "sweet potato"
  - "さつまいも"        
  - "芋"
  - "スイーツ"
  - "カフェ"
  - "菓子"
  - "candy"
  - "うなぎ"
  - "鰻"
  - "海鮮"
  - "飯"
  - "フルーツ"
  - "ソフトクリーム"
  - "せんべい"



events:
  - "event"
  - "イベント"
  - "festival"
  - "祭り"
  - "まつり"
  - "Maturi"
  - "aniversary"
  - "celebration"
  - "firework"
  - "花火"
  - "Hanabi"
  - "parade"
  - "川越まつり"       
  - "山車"   
  - "ライトアップ"          

nature:
  - "自然"
  - "nature"
  - "sakura"
  - "桜"
  - "cherry blossom"
  - "autumn"
  - "紅葉"
  - "風鈴"
  - "テント"
  - "camping"
  - "キャンプ"     
  - "田んぼ"  
  - "釣り"       
