heritage:
  - "temple"
  - "寺"
  - "shrine"
  - "神社"
  - "castle"
  - "城"
  - "蔵"           
  - "時の鐘"           
  - "喜多院"           
  - "氷川神社"           
  - "歴史"  
  - "historic"   

food:
  - "ramen"
  - "ラーメン"
  - "sushi"
  - "寿司"
  - "グルメ"
  - "sweet potato"
  - "さつまいも"        # Kawagoe’s specialty
  - "芋"
  - "スイーツ"
  - "食べ歩き"
  - "川越グルメ"
  - "埼玉グルメ"
  - "食事"
  - "food"
  - "料理"
  - "ランチ"
  - "ディナー"
  - "カフェ"
  - "お菓子横丁"
  - "candy"
  - "うなぎ"
  - "鰻"
  - "海鮮"

events:
  - "event"
  - "イベント"
  - "festival"
  - "祭り"
  - "fireworks"
  - "花火"
  - "parade"
  - "川越まつり"       
  - "山車"   
  - "ライトアップ"          

nature:
  - "sakura"
  - "桜"
  - "cherry blossom"
  - "autumn"
  - "紅葉"
  - "風鈴"
  - "テント"
  - "camping"
  - "キャンプ"              
