category_map:
  1: "Film & Animation"
  2: "Autos & Vehicles"
  10: "Music"
  15: "Pets & Animals"
  17: "Sports"
  19: "Travel & Events"
  20: "Gaming"
  22: "People & Blogs"
  24: "Entertainment"
  27: "Education"
  28: "Science & Technology"